# Generated by Django 4.1.1 on 2022-09-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejalar',
            name='student',
        ),
    ]
