# Generated by Django 4.1.1 on 2022-09-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_remove_rejalar_user_rejalar_student_student_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejalar',
            old_name='Student',
            new_name='student',
        ),
    ]
